spring:
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: ClusterScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
            dataSource: myDS
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 8
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          dataSource:
            myDS:
              driver: com.mysql.jdbc.Driver
              URL: jdbc:mysql://localhost:3306/quartz?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
              user: root
              password: 670317483Sgy?
              maxConnections: 10
    job-store-type: jdbc
    # jdbc:
#     initialize-schema: never